http:
  address: localhost:8080
  metrics:
    enable: true
    token: insecure
  proxy:
    enable: true
    upstreams:
      default: "http://127.0.0.1:8081"
  # FIXME: remove after yaml unmarshaler get a fix for inline structs
  session:
    enable: false
  csrf:
    enable: false
